name: Erlang CI

on: [push, pull_request]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        erlang:  ["18.3", "21.3", "latest"]
    runs-on: ubuntu-latest

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v2
    - name: Get deps
      run: rebar3 get-deps
    - name: Compile
      run: rebar3 compile xref
    - name: Run tests
      run: rebar3 eunit
